### PR TITLE
Fix shadowed variables warnings

### PR DESCRIPTION
**Pull request by Constantine-Fry**
We have enabled warnings `Hidden Shadow Variables` in our Xcode project. So Xcode shows warning for and it's basically strange idea to reassign self in a block. 
```objc
__strong typeof(weakSelf) self = weakSelf;
```

### CODE REVIEW

**Comment by everic** [comment]
Hello

With https://github.com/evernote/evernote-cloud-sdk-ios/commit/8a030ffefbda1f6c7dc087e73799b41a94d59508 the code should not have this warning any more

Just curious, where do you turn on 'Hidden Shadow Variables' setting? I cannot find this toggle in Xcode 6.2 and 6.3 beta's build setting. Thank you.

**Comment by Constantine-Fry** [comment]
Whopps, it's actually called `Hidden Local Variables` or `GCC_WARN_SHADOW`.


screen shot 2015-04-09 at 21 33 13

**Comment by everic** [comment]
Do you still have this warning with the latest code?

**Comment by Constantine-Fry** [comment]
I did not update to latest code yet. But I believe it should work well for me, because you reverted changes.

Thank you.

**Pull request closed without merging**
